### ISSUE TITLE
calling `pip install python-inspector` installs different package

### ISSUE THREAD

**Issue by maxhbr** [nexB/python-inspector#23]
Hey, your README says `pip install python-inspector`, but that installs https://github.com/sebdah/python-inspector for me ;)

**Comment by maxhbr** [comment]
```
$ cat /usr/local/lib/python3.8/dist-packages/python_inspector-0.2.0.dist-info/METADATA
Metadata-Version: 2.1
Name: python-inspector
Version: 0.2.0
Summary: Track down which Python module and script that called your method. Debug tool.
Home-page: http://github.com/sebdah/python-inspector
Author: Sebastian Dahlgren
Author-email: sebastian.dahlgren@gmail.com
License: Apache License, Version 2.0
Keywords: python inspector inspection tracing tracking
Platform: Any
Classifier: Development Status :: 4 - Beta
Classifier: Environment :: Console
Classifier: License :: OSI Approved :: Apache Software License
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python

UNKNOWN
```

**Comment by pombredanne** [comment]
@maxhbr good catch!
Let me update the doc right away... and we likely want to rename this

**Comment by pombredanne** [comment]
@sebdah hey! you own the PyPI python-inspector name at https://pypi.org/project/python-inspector/ ... but it may not be something you still maintain or need after 10 years? 

I was wondering if you would hand over the name? If not, I will rename this package to something else.
Thank you for your kind consideration!

**Comment by pombredanne** [comment]
@sebdah it worked. Thank you ++ for your speedy and gentle handling of the "baton". You rock!
https://pypi.org/project/python-inspector/0.5.0/

**Comment by pombredanne** [comment]
@maxhbr Thank you ++ for this report!
