### ISSUE TITLE
Create dependency resolver command line tool

### ISSUE THREAD

**Issue by mjherzog** [nexB/python-inspector#4]
python-inspector will be written in Python and distributed as a PyPi package:
- We will publish released builds to PyPI. 
- We will create unit tests and use our existing toolchain template for the builds.
- The software will be licensed under Apache 2.0 with a nexB copyright

**Comment by pombredanne** [comment]
This has been completed and merged

**Comment by pombredanne** [comment]
See also https://pypi.org/project/python-inspector/
