### ISSUE TITLE
Find a way to represent cyclic dependency on tree representation 

### ISSUE THREAD

**Issue by TG1999** [nexB/python-inspector#45]
Container-inspector depends on extractcode https://github.com/nexB/python-inspector/pull/42/files#diff-8533e0a243fd80bf45849f9fba5618b164a7b2ac7308a131ea82f384176420feR862 and extractcode depends on container-inspector https://github.com/nexB/python-inspector/pull/42/files#diff-8533e0a243fd80bf45849f9fba5618b164a7b2ac7308a131ea82f384176420feR1024 so when we try to provide a tree resolution for this it forms an infinite recursion.

**Comment by TG1999** [comment]
Cyclic dependencies can't be resolved so no need to represent them, closing this

**Comment by pombredanne** [comment]
> Cyclic dependencies can't be resolved so no need to represent them, closing this

Are you sure?

If there are no conflicting version constraints there is no issue wrt. having cycle as far as I can remember.
