### ISSUE TITLE
Ignore Invalid requirement files

### ISSUE THREAD

**Issue by TG1999** [nexB/python-inspector#55]
Python-inspector doesn't support taking input from setup.py, setup.cfg for now. Raise an error when a file that doesn't match requirements file pattern is given in input.

**Comment by pombredanne** [comment]
@TG1999 IMHO we should NOT raise an error if the file does match a name pattern... rather we should raise an error only when it cannot be parsed.

**Comment by TG1999** [comment]
This https://github.com/nexB/python-inspector/pull/56 helps in not ignoring file on basis of their name but does not close this issue, we still need to define a way to ignore files that are not requirement files.
