### ISSUE TITLE
Package list contains duplicate entries

### ISSUE THREAD

**Issue by mnonnenmacher** [nexB/python-inspector#71]
The package list in the output of python-inspector 0.7.0 contains duplicate entries which are identical except for the download url (one for the .whl, one for .tar.gz). To reproduce run `python-inspector -p 27 -s setup.py --json -` on [this file](https://github.com/oss-review-toolkit/ort/blob/5c6fc850b0b1b0a2734e8de14c9d2b1a7b85cd73/analyzer/src/funTest/assets/projects/synthetic/pip/setup.py).
To reduce the file size and simplify parsing it would be beneficial if the package entry would contain a list of download urls with associated hashes instead. Maybe this can be addressed as part of #68?

**Comment by pombredanne** [comment]
@mnonnenmacher the approach here and in the ScanCode models is that one different package instance is returned for each different download URL. The rationale is that there are cases where the different download (here source and compiled binaries) can contain different set of bundled code and dependencies.

**Comment by mnonnenmacher** [comment]
Does this mean that any other values except for the download URL and the related hashes could be different between to such package instances? Because if not it just seems like unnecessary duplication. Anyway, feel free to close this as the ORT integration of python-inspector can handle the current output.
