### ISSUE TITLE
Provide summary as part of package metadata

### ISSUE THREAD

**Issue by mnonnenmacher** [nexB/python-inspector#74]
Currently the python-inspector provides only the description property for a package, but I would also like to have access to the shorter summary.

Often the descriptions are very long, but for usage in ORT we only need the short summary, compare for example the summary and description for this package:
https://pypi.org/pypi/isodate/0.6.1/json

**Comment by pombredanne** [comment]
We use the ScanCode data model to ensure we have consistent output format for all package ecosystems which is to have only one description field. When a given package manifest provides two descriptions (like here short and long) we put the short one as the first line of the description, and the long one afterwards.
Here the first line of the description would be `An ISO 8601 date/time/duration parser and formatter`

**Comment by pombredanne** [comment]
This has helped treat consistently the cases of short only, long only, and short + long

**Comment by mnonnenmacher** [comment]
Thanks for the explanation, I could only take the first line then. I had a short look at the code and it seems to do what you describe, however for all packages I checked I only get the long description, so for example for the isodate package the description in the python-inspector output starts with:

```
ISO 8601 date/time parser
=========================
```

This is unfortunate for packages like this where the description does not start with text: https://pypi.org/pypi/six/1.16.0/json

This happens for all test projects we use in ORT and can for example be reproduced by running `python-inspector --python-version 27 --json-pdt inspector-pdt.json --setup-py setup.py --analyze-setup-py-insecurely` on [this file](https://github.com/spdx/tools-python/blob/a48022e65a8897d0e4f2e93d8e53695d2c13ea23/setup.py). Mabye @TG1999 could have a look at this?

**Comment by mnonnenmacher** [comment]
@pombredanne I can confirm that this is fixed now that #84 is merged (also see https://github.com/oss-review-toolkit/ort/pull/6021).
