### ISSUE TITLE
Provide classifiers in python-inspector output

### ISSUE THREAD

**Issue by mnonnenmacher** [nexB/python-inspector#81]
ORT uses the classifiers as a fallback to get license information for a package. For example, this package does not provide a declared license but has the classifier `License :: OSI Approved :: BSD License`:
https://pypi.org/pypi/click/6.7/json

This is missing the version of the BSD license, but it is still much better than having no license information at all.

**Comment by mnonnenmacher** [comment]
Thanks for the explanation @pombredanne, but with python-inspector I only get the classifiers in the `files` section, the entries in the `packages` section only have a plain string as declared license:

```json
{
  ...
  "files": [
    {
      ...
      "package_data": [
        {
          "type": "pypi",
          "namespace": null,
          "name": "spdx-tools",
          "version": "0.5.4",
          ...
          "declared_license": {
            "license": "Apache-2.0",
            "classifiers": [
              "License :: OSI Approved :: Apache Software License"
            ]
          },
          ...
        }
      ]
    }
  ],
  ...
  "packages": [
    {
      "type": "pypi",
      "namespace": null,
      "name": "isodate",
      "version": "0.6.1",
      ...
      "declared_license": "BSD",
      ...
    },
    ...
  ]
}
```

The package above should also have the classifier "License :: OSI Approved :: BSD License" in the declared license according to your description: https://pypi.org/pypi/isodate/0.6.1/json

**Comment by sschuberth** [comment]
> we can compute a proper normalized license from that license "declaration"

Note that, however, you cannot normalize e.g. "BSD License" to *BSD-3-Clause* as it theoretically could be *BSD-2-Clause* as well.

**Comment by pombredanne** [comment]
@mnonnenmacher 

> The package above should also have the classifier "License :: OSI Approved :: BSD License" in the declared license according to your description: https://pypi.org/pypi/isodate/0.6.1/json

Correct: this the bug I mentioned

**Comment by pombredanne** [comment]
@sschuberth  re:
 > Note that, however, you cannot normalize e.g. "BSD License" to BSD-3-Clause as it theoretically could be BSD-2-Clause as well.

ScanCode now reports a BSD-3-Clause with a lowered relevance in these cases. Please see https://github.com/mandiant/Vulnerability-Disclosures/issues/5#issuecomment-1275165629 for an extensive discussion including some FOSS-savvy lawyers comments for the rationale.

**Comment by TG1999** [comment]
Solved in https://github.com/nexB/python-inspector/tree/v0.8.5

**Comment by mnonnenmacher** [comment]
Thanks @TG1999 , I can confirm that this is fixed now (also see https://github.com/oss-review-toolkit/ort/pull/6021).
