### ISSUE TITLE
requirements.txt has recursive calls

### ISSUE THREAD

**Issue by gmathiou4** [nexB/python-inspector#88]
Hi community,

The requirements.txt has recursive calls as below, is it possible for python-inspector to support recursive calls?

```
# Only installs requirements for deployments
PyYAML==6.0
retrying==1.3.3
shapely==1.7.1
simplekml==1.3.5
-r requirements/com.txt
-r requirements/dev.txt
```

**Comment by TG1999** [comment]
@gmathiou4 thanks for raising this issue, this will be solved in #89
