### ISSUE TITLE
Inconsistent type of `resolvedDependenciesGraph`

### ISSUE THREAD

**Issue by mnonnenmacher** [nexB/python-inspector#94]
With the fix for #86 the type of the `resolvedDependenciesGraph` property is now inconsistent. Usually the property is an array, but if the dependency graph is empty it is an empty object `{}` instead of an empty array:

https://github.com/nexB/python-inspector/blob/0da2e84124fa10de7b2b005240b8de38c0095286/tests/data/setup/no-direct-dependencies-setup.py-expected.json#L84

This makes the deserialization unnecessarily complex.

**Comment by TG1999** [comment]
@mnonnenmacher thanks for raising this, I am having a look on this.

**Comment by TG1999** [comment]
This is fixed in https://pypi.org/project/python-inspector/0.9.2/ , please check and let us know.

**Comment by mnonnenmacher** [comment]
Thanks @TG1999, the fix works.
